import React, { useState } from "react";
import Hero from "@/components/Hero";
import Footer from "@/components/Footer";
import Portfolio from "@/components/Portfolio";
import Nav from "@/components/Nav";
import Link from "next/link";
import Head from "next/head";
import Portfolio2 from "@/components/Portfolio";

export default function Home() {
  const [education, setEducation] = useState([]);
  const [experience, setExperience] = useState([]);
  const [skills, setSkills] = useState([]);

  return (
    <>
      <Head>
        <title>Interactive Resume Generator</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Nav />
      <Hero />
      <Portfolio2 />
      {/* <Portfolio
        education={education}
        experience={experience}
        skills={skills}
      /> */}
      <Footer />
    </>
  );
}
