import React, { useState } from "react";
import Hero from "@/components/Hero";
import Footer from "@/components/Footer";
import Portfolio from "@/components/Portfolio";
import Nav from "@/components/Nav";
import Link from "next/link";
import Head from "next/head";
import Main from "@/components/Main";
import { useAuth } from "@/contexts/auth";

export default function Home() {
  const [education, setEducation] = useState([]);
  const [experience, setExperience] = useState([]);
  const [skills, setSkills] = useState([]);

  return (
    <>
      <Head>
        <title>Interactive Resume Generator</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Nav />
      <Main />
      <Footer />
    </>
  );
}
